server:
  port: 80
  ssl:
    enabled: true
    key-store: /home/ec2-user/cert/letsencrypt.jks
    key-store-password: "{cipher}be015ff71f9a23702df5f33e533af44446a5c62d77b39c6a18f15be338367cbc"
    key-password: "{cipher}be015ff71f9a23702df5f33e533af44446a5c62d77b39c6a18f15be338367cbc"
      
spring:
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          ws-project:
            client-id: "{cipher}8792efbb10ee0e7637154a565b069234298b3cd2cab887db6031e9fcbc36a099"
            client-secret: "{cipher}a9aebad181d46568fb4b19d1eb5028108ba691bdeafafcf4afd23f7090e34118bdfef9adbb4793c5a56c3ede06a8e95e2860d512b263e8b0dab580ca4fe9d3a3"

logging:
  level:
    com.wsproject.clientsvr: debug
                        
custom:
  api-base-uri: http://mslim8803.shop:5555/api
  authsvr-base-uri: http://mslim8803.shop:8901 # AWS에 올린 후에 다시 주석처리하고 해보자.
  